
name: make_favicon

on:
  workflow_dispatch

jobs:
  instal:
    name: Runs Data Sync Task
    runs-on: ubuntu-latest
    steps:
      - name: install package
        run: pip install favicons
      - name: make favicon
        run: python make_favicon.py